WebStore/Controllers/CatalogController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using AutoMapper;
using WebStore.Domain.Filters;
using WebStore.Domain.Models.Product;
using WebStore.Interfaces.Services;
using Microsoft.Extensions.Configuration;
using WebStore.Domain.Models;

namespace WebStore.Controllers
{
    public class CatalogController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IProductData _productData;
        private readonly IConfiguration _configuration;

        public CatalogController(IProductData productData, IConfiguration configuration, IMapper mapper)
        {
            _productData = productData;
            _mapper = mapper;
            _configuration = configuration;
        }

        public IActionResult Shop(int? sectionId, int? brandId, int page = 1)
        {
            var pageSize = int.Parse(_configuration["PageSize"]);

            var pagedProducts = _productData.GetProducts(new ProductFilter
            {
                BrandId = brandId,
                SectionId = sectionId,
                Page = page,
                PageSize = pageSize
            });

            var model = new CatalogViewModel()
            {
                BrandId = brandId,
                SectionId = sectionId,
                Products = _mapper.Map<IEnumerable<ProductViewModel>>(pagedProducts.Products)
                    .ToList(),
                PageViewModel = new PageViewModel
                {
                    PageSize = pageSize,
                    PageNumber = page,
                    TotalItems = pagedProducts.TotalCount
                }
            };

            return View(model);
        }

        public IActionResult ProductDetails(int id)
        {
            var product = _productData.GetProductById(id);

            if (product == null)
                return NotFound();

            var model = _mapper.Map<ProductViewModel>(product);

            return View(model);
        }

        public IActionResult GetFilteredItems(int? sectionId, int? brandId, int
            page = 1)
        {
            var productsModel = GetProducts(sectionId, 
                brandId,
                page, 
                out var totalCount);

            return PartialView("Partial/_Features", productsModel);
        }

        private IEnumerable<ProductViewModel> GetProducts(int? sectionId, int?
            brandId, int page, out int totalCount)
        {
            var products = _productData.GetProducts(new ProductFilter
            {
                BrandId = brandId,
                SectionId = sectionId,
                Page = page,
                PageSize = int.Parse(_configuration["PageSize"])
            });
            totalCount = products.TotalCount;

            return _mapper.Map<List<ProductViewModel>>(products.Products);
        }
    }
}

WebStore/Controllers/ProfileController.cs
using System.Collections.Generic;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebStore.Domain.Models.Order;
using WebStore.Interfaces.Services;

namespace WebStore.Controllers
{
    [Authorize]
    public class ProfileController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IOrdersData _ordersData;
        public ProfileController(IOrdersData ordersData, IMapper mapper)
        {

            _mapper = mapper;
            _ordersData = ordersData;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Orders()
        {
            var orders = _ordersData.GetUserOrders(User.Identity.Name);

            var orderModels = _mapper.Map<IEnumerable<UserOrderViewModel>>(orders);

            return View(orderModels);
        }
    }
}

WebStore/ViewComponents/BrandsViewComponent.cs
using System;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using AutoMapper;
using WebStore.Domain.Models.Product;
using WebStore.Interfaces.Services;

namespace WebStore.ViewComponents
{
    public class BrandsViewComponent : ViewComponent
    {
        private readonly IMapper _mapper;
        private readonly IProductData _productData;

        public BrandsViewComponent(IProductData productData, IMapper mapper)
        {
            _mapper = mapper;
            _productData = productData;
        }

        public IViewComponentResult Invoke(string brandId)
        {
            Int32.TryParse(brandId, out var brandIdInt);

            var brands = GetBrands();

            return View(new BrandCompleteViewModel
            {
                Brands = brands,
                CurrentBrandId = brandIdInt
            });
        }

        private IEnumerable<BrandViewModel> GetBrands()
        {
            var brands = _mapper.Map<IEnumerable<BrandViewModel>>(
                _productData.GetBrands()).ToList();

            for (int i = 0; i < brands.Count; i++)
                brands[i].ProductsCount = _productData.GetBrandProductCount(brands[i].Id);

            return brands;
        }

    }
}

WebStore/ViewComponents/SectionsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using AutoMapper;
using WebStore.Domain.Models.Product;
using WebStore.Interfaces.Services;

namespace WebStore.ViewComponents
{
    public class SectionsViewComponent : ViewComponent
    {
        private readonly IMapper _mapper;
        private IProductData _productData;

        public SectionsViewComponent(IProductData productData, IMapper mapper)
        {
            _mapper = mapper;
            _productData = productData;
        }

        public IViewComponentResult Invoke(string sectionId)
        {
            int.TryParse(sectionId, out var sectionIdInt);

            var sections = GetSections(sectionIdInt, out var parentSectionId);

            return View(new SectionCompleteViewModel
            {
                Sections = sections,
                CurrentSectionId = sectionIdInt,
                CurrentParentSectionId = parentSectionId
            });
        }

        private List<SectionViewModel> GetSections(int? sectionId, out int? parentSectionId)
        {
            parentSectionId = null;

            var allSections = _productData.GetSections();

            var parentCategories = allSections.Where(p => !p.ParentId.HasValue).ToList();

            var parentSections = new List<SectionViewModel>();
            foreach (var parentCategory in parentCategories)
            {
                parentSections.Add(new SectionViewModel()
                {
                    Id = parentCategory.Id,
                    Name = parentCategory.Name,
                    Order = parentCategory.Order,
                    ParentSectionView = null
                });
            }
            foreach (var sectionViewModel in parentSections)
            {
                var childCategories = allSections.Where(c => c.ParentId.Equals(sectionViewModel.Id));
                foreach (var childCategory in childCategories)
                {
                    if (childCategory.Id == sectionId)
                        parentSectionId = sectionViewModel.Id;

                    sectionViewModel.ChildSections.Add(new SectionViewModel
                    {
                        Id = childCategory.Id,
                        Name = childCategory.Name,
                        Order = childCategory.Order,
                        ParentSectionView = sectionViewModel
                    });
                }
                sectionViewModel.ChildSections = sectionViewModel.ChildSections.OrderBy(c =>
                c.Order).ToList();
            }
            parentSections = parentSections.OrderBy(c => c.Order).ToList();
            return parentSections;
        }

    }
}

WebStore/Views/Shared/Partial/_Features.cshtml
@model IEnumerable<ProductViewModel>
@{
    var isBrand = Context.Request.Query.ContainsKey("brandId");
}

<div class="features_items">
    <!--features_items-->
    <h2 class="title text-center">Goods</h2>

    @foreach (var item in Model)
    {
        <div class="col-sm-4">
            <div class="product-image-wrapper">
                <div class="single-products">
                    <div class="productinfo text-center">
                        @if (isBrand)
                        {
                            <a asp-controller="Catalog"
                               asp-action="ProductDetails"
                               asp-route-id="@item.Id"
                               asp-route-fromBrand="true">
                                <img src="~/images/shop/@item.ImageUrl" alt="" />
                                <h2>@item.Price.ToString("C")</h2>
                                <p>@item.Name</p>
                            </a>
                        }
                        else
                        {
                            <a asp-controller="Catalog"
                               asp-action="ProductDetails"
                               asp-route-id="@item.Id">
                                <img src="~/images/shop/@item.ImageUrl" alt="" />
                                <h2>@item.Price.ToString("C")</h2>
                                <p>@item.Name</p>
                            </a>
                        }

                        <a href="#"
                           data-id="@item.Id"
                           class="btn btn-default add-to-cart callAddToCart">
                            <i class="fa fa-shopping-cart"></i>Add to backet
                        </a>
                    </div>
                </div>
                <div class="choose">
                    <ul class="nav nav-pills nav-justified">
                        <li><a href="#"><i class="fa fa-plus-square"></i>Add to wish list</a></li>
                        <li><a href="#"><i class="fa fa-plus-square"></i>Add for compare</a></li>
                    </ul>
                </div>
            </div>
        </div>
    }
</div><!--features_items-->

WebStore/Views/Shared/Partial/_Footer.cshtml
<footer id="footer"><!--Footer-->
    <div class="footer-top">
        <div class="container">
            <div class="row">
                <div class="col-sm-2">
                    <div class="companyinfo">
                        <h2>
                            <span>e</span>-shopper
                        </h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit,sed do eiusmod tempor</p>
                    </div>
                </div>
                <div class="col-sm-7">
                    <div class="col-sm-3">
                        <div class="video-gallery text-center">
                            <a href="#">
                                <div class="iframe-img">
                                    <img src="~/images/home/iframe1.png" alt="" />
                                </div>
                                <div class="overlay-icon">
                                    <i class="fa fa-play-circle-o"></i>
                                </div>
                            </a>
                            <p>Circle of Hands</p>
                            <h2>24 DEC 2019</h2>
                        </div>
                    </div>

                    <div class="col-sm-3">
                        <div class="video-gallery text-center">
                            <a href="#">
                                <div class="iframe-img">
                                    <img src="~/images/home/iframe2.png" alt="" />
                                </div>
                                <div class="overlay-icon">
                                    <i class="fa fa-play-circle-o"></i>
                                </div>
                            </a>
                            <p>Circle of Hands</p>
                            <h2>24 DEC 2019</h2>
                        </div>
                    </div>

                    <div class="col-sm-3">
                        <div class="video-gallery text-center">
                            <a href="#">
                                <div class="iframe-img">
                                    <img src="~/images/home/iframe3.png" alt="" />
                                </div>
                                <div class="overlay-icon">
                                    <i class="fa fa-play-circle-o"></i>
                                </div>
                            </a>
                            <p>Circle of Hands</p>
                            <h2>24 DEC 2019</h2>
                        </div>
                    </div>

                    <div class="col-sm-3">
                        <div class="video-gallery text-center">
                            <a href="#">
                                <div class="iframe-img">
                                    <img src="~/images/home/iframe4.png" alt="" />
                                </div>
                                <div class="overlay-icon">
                                    <i class="fa fa-play-circle-o"></i>
                                </div>
                            </a>
                            <p>Circle of Hands</p>
                            <h2>24 DEC 2019</h2>
                        </div>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="address">
                        <img src="~/images/home/map.png" alt="" />
                        <p>505 S Atlantic Ave Virginia Beach, VA(Virginia)</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="footer-widget">
        <div class="container">
            <div class="row">
                <div class="col-sm-2">
                    <div class="single-widget">
                        <h2>Service</h2>
                        <ul class="nav nav-pills nav-stacked">
                            <li><a href="#">Online Help</a></li>
                            <li><a href="#">Contact Us</a></li>
                            <li><a href="#">Order Status</a></li>
                            <li><a href="#">Change Location</a></li>
                            <li><a href="#">FAQ’s</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="single-widget">
                        <h2>Quock Shop</h2>
                        <ul class="nav nav-pills nav-stacked">
                            <li><a href="#">T-Shirt</a></li>
                            <li><a href="#">Mens</a></li>
                            <li><a href="#">Womens</a></li>
                            <li><a href="#">Gift Cards</a></li>
                            <li><a href="#">Shoes</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="single-widget">
                        <h2>Policies</h2>
                        <ul class="nav nav-pills nav-stacked">
                            <li><a href="#">Terms of Use</a></li>
                            <li><a href="#">Privecy Policy</a></li>
                            <li><a href="#">Refund Policy</a></li>
                            <li><a href="#">Billing System</a></li>
                            <li><a href="#">Ticket System</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="single-widget">
                        <h2>About Shopper</h2>
                        <ul class="nav nav-pills nav-stacked">
                            <li><a href="#">Company Information</a></li>
                            <li><a href="#">Careers</a></li>
                            <li><a href="#">Store Location</a></li>
                            <li><a href="#">Affillate Program</a></li>
                            <li><a href="#">Copyright</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-3 col-sm-offset-1">
                    <div class="single-widget">
                        <h2>About Shopper</h2>
                        <form action="#" class="searchform">
                            <input type="text" placeholder="Your email address" />
                            <button type="submit" class="btn btn-default"><i class="fa fa-arrow-circle-o-right"></i></button>
                            <p>
                                Get the most recent updates from <br />our site and be updated your self...
                            </p>
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <div class="footer-bottom">
        <div class="container">
            <div class="row">
                <p class="pull-left">Copyright © 2019 E-SHOPPER Inc. All rights reserved.</p>
                <p class="pull-right">
                    Designed by <span><a target="_blank" href="http://www.themeum.com">Themeum</a></span>
                </p>
            </div>
        </div>
    </div>

</footer><!--/Footer-->

WebStore/Views/Shared/Partial/_HeadLinks.cshtml
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<meta name="author" content="">


<environment include="Development">
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/font-awesome.min.css" rel="stylesheet">
    <link href="~/css/prettyPhoto.css" rel="stylesheet">
    <link href="~/css/price-range.css" rel="stylesheet">
    <link href="~/css/animate.css" rel="stylesheet">
    <link href="~/css/main.css" rel="stylesheet">
    <link href="~/css/responsive.css" rel="stylesheet">
</environment>
<environment exclude="Development">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/font-awesome.min.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/bundled/site.min.css" asp-append-version="true"/>
</environment>

<link href='http://fonts.googleapis.com/css?family=Roboto:400,300,400italic,500,700,100' rel='stylesheet' type='text/css' />
<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,800,300,600,700' rel='stylesheet' type='text/css' />
<link href='http://fonts.googleapis.com/css?family=Abel' rel='stylesheet' type='text/css' />


<!--[if lt IE 9]>
    <script src="~/js/html5shiv.js"></script>
<![endif]-->

WebStore/Views/Shared/Partial/_Header.cshtml
<header id="header">
    <!--header-->
    
    <div class="header_top">
        <!--header_top-->
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <div class="contactinfo">
                        <ul class="nav nav-pills">
                            <li><a href="#"><i class="fa fa-phone"></i> +3 99 00 88 722</a></li>
                            <li><a href="#"><i class="fa fa-envelope"></i> info@domain.com</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="social-icons pull-right">
                        <ul class="nav navbar-nav">
                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                            <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div><!--/header_top-->

    <div class="header-middle">
        <!--header-middle-->
        <div class="container">
            <div class="row">
                <div class="col-sm-3">
                    <div class="logo pull-left">
                        <a asp-controller="Home"
                           asp-action="Index"><img src="~/images/home/logo.png" alt="" /></a>
                    </div>

                </div>
                <div class="col-sm-6">
                    <div class="shop-menu pull-left">
                        <ul class="nav navbar-nav">
                            <li><a href="#"><i class="fa fa-star"></i> Wishlist</a></li>
                            <li>
                                <a asp-controller="Cart"
                                   asp-action="Checkout"
                                   is-active-route><i class="fa fa-crosshairs"></i> Checkout</a>
                            </li>
                            <li>
                                <a asp-controller="Cart"
                                   asp-action="Details"
                                   is-active-route><i class="fa fa-shopping-cart"></i>Backet</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="pull-left" id="cartContainer">

                        @await Component.InvokeAsync( "Cart" )

                    </div>

                    <div class="pull-right">

                        @await Html.PartialAsync( "Partial/_LoginLogout" )

                    </div>
                </div>
            </div>
        </div>
    </div><!--/header-middle-->

    <div class="header-bottom">
        <!--header-bottom-->
        <div class="container">
            <div class="row">
                <div class="col-sm-9">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div class="mainmenu pull-left">
                        <ul class="nav navbar-nav collapse navbar-collapse">
                            <li>
                                <a asp-controller="Home"
                                   asp-action="Index"
                                   is-active-route>Home</a>
                            </li>
                            <li class="dropdown">
                                <a asp-controller="Catalog"
                                   asp-action="Shop"
                                   is-active-route
                                   ignore-action>Shop<i class="fa fa-angle-down"></i></a>
                                <ul role="menu" class="sub-menu">
                                    <li>
                                        <a asp-controller="Cart"
                                           asp-action="Details"
                                           is-active-route>Backet</a>
                                    </li>
                                    <li>
                                        <a asp-controller="Account"
                                           asp-action="Login"
                                           is-active-route>Login</a>
                                    </li>
                                    <li>
                                        <a asp-controller="Account"
                                           asp-action="Register"
                                           is-active-route>Registration</a>
                                    </li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#">Blog<i class="fa fa-angle-down"></i></a>
                                <ul role="menu" class="sub-menu">
                                    <li>
                                        <a asp-controller="Home"
                                           asp-action="Blog"
                                           is-active-route>Blog List</a>
                                    </li>
                                    <li>
                                        <a asp-controller="Home"
                                           asp-action="BlogSingle">Blog Single</a>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a asp-controller="Home"
                                   asp-action="Contact"
                                   is-active-route>Contact</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="search_box pull-right">
                        <input type="text" placeholder="Search" />
                    </div>
                </div>
            </div>
        </div>
    </div><!--/header-bottom-->
</header><!--/header-->

WebStore/Views/Shared/Partial/_LeftSideBar.cshtml
<div class="left-sidebar">
    
    @await Component.InvokeAsync("Sections",
        new { sectionId = Context.Request.Query["sectionId"].ToString() })

    @await Component.InvokeAsync("Brands",
        new  { brandId = Context.Request.Query["brandId"].ToString() })

    <div class="price-range"><!--price-range-->
        <h2>Price Range</h2>
        <div class="well text-center">
            <input type="text" class="span2" value="" data-slider-min="0" data-slider-max="600" data-slider-step="5" data-slider-value="[250,450]" id="sl2"><br />
            <b class="pull-left">$ 0</b> <b class="pull-right">$ 600</b>
        </div>
    </div><!--/price-range-->

    <div class="shipping text-center">
        <!--shipping-->
        <img src="~/images/home/shipping.jpg" alt="" />
    </div><!--/shipping-->

</div>

WebStore/Views/Shared/Partial/_LoginLogout.cshtml
@if (User.Identity.IsAuthenticated)
{
    <span>Hello, <a asp-action="Index"
                           asp-controller="Profile">@User.Identity.Name</a></span>
    <form method="post" asp-controller="Account"
          asp-action="Logout"
          asp-antiforgery="true">
        <input type="submit" value="Login" class="btn btn-default" />
    </form>
    @if (User.IsInRole("Administrator"))
     {
         <a asp-action="Index" 
            asp-controller="Home"
            asp-area="Admin"
            class="btn btn-sm btn-link">Admin page</a>
     }
}
else
{
    <div class="btn-group pull-right">
        <a asp-action="Login" asp-controller="Account" class="btn btn-default">Login</a>
        <a asp-action="Register" asp-controller="Account" class="btn btn-default">Registration</a>
    </div>
}

WebStore/Views/Shared/Partial/_ProfileMenu.cshtml
<div class="panel-group category-products">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title"><a asp-controller="Profile"
                                       asp-action="Index">Profile</a></h4>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title"><a asp-controller="Profile"
                                       asp-action="Orders">My orders</a></h4>
        </div>
    </div>
</div>

WebStore/Views/Shared/Partial/_Scripts.cshtml
<environment include="Development">
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/js/jquery.scrollUp.min.js"></script>
    <script src="~/js/price-range.js"></script>
    <script src="~/js/jquery.prettyPhoto.js"></script>
    <script src="~/js/main.js"></script>
    <script src="~/js/custom/cart/Cart.js"></script>
    <script src="~/js/custom/loadingOverlay/loadingoverlay.min.js"></script>
</environment>
<environment exclude="Development">
    <script src="~/bundled/site.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
    <script src="~/js/jquery.scrollUp.min.js" asp-append-version="true"></script>
    <script src="~/js/custom/loadingOverlay/loadingoverlay.min.js" asp-append-version="true"></script>
</environment>
<script type="text/javascript">
    $(function() {
        Cart.init({
            addToCartLink: '@Url.Action("AddToCart", "Cart")',
            getCartViewLink: '@Url.Action("GetCartView", "Cart")',
            removeFromCartLink: '@Url.Action("RemoveFromCart", "Cart")',
            decrementLink: '@Url.Action("DecrementFromCart", "Cart")'
        });
    });
</script>